# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'item-share-app' do

  project 'item-share-app.xcodeproj'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ItemShareApp
  pod 'Parse'
  pod 'ParseUI'
  pod 'DZNEmptyDataSet'
  pod 'Stripe'
  pod 'AFNetworking'
  pod 'JTCalendar', '~> 2.0'
  pod 'ClusterKit/MapKit'

end
