# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ItemShareApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ItemShareApp
  pod 'Parse'

  target 'ItemShareAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ItemShareAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
